autofat:
  network:
    - name: rpi
      ip: 10.0.1.99
      credentials:
        user: vortex
        pwd: ${RPI_PWD}
    - name: xavier
      ip: 10.0.1.100
      credentials:
        user: vortex
        pwd: ${XAVIER_PWD}