autofat:
  network:
    - name: rpi
      ip: 10.0.1.99
      credientials:
        user: ubuntu
        pwd: ${RPI_PWD}
    - name: xavier
      ip: 10.0.1.100
      credientials:
        user: ubuntu
        pwd: ${XAVIER_PWD}
        
  fat:
    - name: devops
      file: devops.yaml
      order: 1
      steps: 0

